### ISSUE TITLE
Add support for SSL libraries 

### ISSUE THREAD

**Issue by ChrisMcGowan** [shieldproject/shield-addon-postgres-boshrelease#1]
When using SSL for pg_dump, the current postgres-9.6 binaries are build without SSL support via the OpenSSL binaries.  This can be done fairly easily but adding `--with-openssl` on the configure line for the build -> https://github.com/shieldproject/shield-addon-postgres-boshrelease/blob/master/packages/shield-addon-postgres-9.6/packaging#L7

Since this would increase the size of the compiled bits - maybe make it a deployment option when co-locating the release?

**Comment by jhunt** [comment]
Added in #2, which was merged a while back.  Closing this.
