### ISSUE TITLE
pg_dump: aborting because of server version mismatch

### ISSUE THREAD

**Issue by Klojo** [shieldproject/shield-addon-postgres-boshrelease#3]
Running backup task (using bzip2 compression)
=============================================
pg_dump: server version: 11.2; pg_dump version: 9.6.6
pg_dump: aborting because of server version mismatch
Unable to exec '/var/vcap/packages/shield-addon-postgres-9.6/bin/pg_dump': exit status 1

please can you upgrade the pg_dump version to 11.2
https://www.postgresql.org/ftp/source/v11.2/

**Comment by jhunt** [comment]
v1.0.2 release of this add-now has PostgreSQL 11.2 available, as `shield-addon-postgres-11`

https://github.com/shieldproject/shield-addon-postgres-boshrelease/releases/tag/v1.0.2

Enjoy!
